---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "surrealdb.fullname" . }}
  labels:
    app: {{ template "surrealdb.name" . }}
    chart: {{ template "surrealdb.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: surrealdb
      port: {{ .Values.surrealdb.port }}
      targetPort: surrealdb
  selector:
    app: {{ template "surrealdb.name" . }}
    release: {{ .Release.Name | quote }}
