{{- if .Values.pdp.isEnabled }}
---
######################################################################
# Envoy Config with External Authorization filter that will query OPA.
######################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-prxy-cnfg" | quote }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: upstream-service
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  grpc_service:
                    envoy_grpc:
                      cluster_name: {{ .Values.pdp.envoy.config_ext_authz.grpc_service.envoy_grpc.cluster_name }}
                    timeout: {{ .Values.pdp.envoy.config_ext_authz.grpc_service.timeout }}
                  transport_api_version: {{ .Values.pdp.envoy.config_ext_authz.transport_api_version }}
                  with_request_body:
                    max_request_bytes: {{ .Values.pdp.envoy.config_ext_authz.with_request_body.max_request_bytes | int }}
                    allow_partial_message: {{ .Values.pdp.envoy.config_ext_authz.with_request_body.allow_partial_message }}
                    pack_as_bytes: {{ .Values.pdp.envoy.config_ext_authz.with_request_body.pack_as_bytes }}
                  failure_mode_allow: {{ .Values.pdp.envoy.config_ext_authz.failure_mode_allow }}
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: opa-envoy
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
        connect_timeout: 0.25s
        load_assignment:
          cluster_name: opa-envoy
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9191
      - name: upstream-service
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: upstream-service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: {{ .Values.pdp.envoy.upstream_service.port | int }}
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
---
{{- end }}
